languageCode = "en"
languageName = "English"
weight = 1
title = "Harija"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/harija.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "My awesome website"
  copyright = "© Harija Wijesinghe"

 [author]
   name = "Harija Wijesinghe"
   image = "img/greatpfp.jpg"
   headline = "Welcome to my site!"
   bio = "Hi, my name is Harija."
   links = [
     { email = "mailto:harija@harija.moe" },
     { link = "https://harija.moe" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
     { discord = "https://discord.gg/7VYXrYpBUr" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
     { github = "https://github.com/harrythezomby" },
     { gitlab = "https://gitlab.com/harijawi58" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { instagram = "https://instagram.com/username" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
     { lastfm = "https://www.last.fm/user/htz-fm" },
     { linkedin = "https://www.linkedin.com/in/harija-wijesinghe-461937252/" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
     { steam = "https://steamcommunity.com/id/harija" },
#     { telegram = "https://t.me/username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://twitter.com/username" },
#     { whatsapp = "https://wa.me/phone-number" },
     { youtube = "https://www.youtube.com/@harrythezomby" },
#     { ko-fi = "https://ko-fi.com/username" },
  ]
