colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = false
mainSections = [ "projects", "posts" ]
disableImageOptimization = false
defaultBackgroundImage = "img/keyboard.jpg"
defaultFeaturedImage = "img/keyboard.jpg"

[header]
layout = "fixed"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
homepageImage = "img/keyboard.jpg"
showRecent = true
showRecentItems = 20
showMoreLink = true
showMoreLinkDest = "/projects"
cardView = true
cardViewScreenWidth = true
layoutBackgroundBlur = true

[article]
showDate = true
showViews = true
showLikes = true
showDateUpdated = false
showAuthor = true
showHero = true
showComments = true
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = false
showAuthorsBadges = false
showWordCount = true
sharingLinks = [ "linkedin", "twitter", "reddit", "pinterest", "facebook", "email", "whatsapp", "telegram" ]

[list]
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showSummary = false
showViews = false
showLikes = false
showTableOfContents = false
showCards = false
groupByYear = true
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = true
heroStyle = "background"
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = false

[term]
showHero = true
heroStyle = "background"
showBreadcrumbs = false
showViews = true
showLikes = true
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false

[firebase]
apiKey = "AIzaSyDvgjd58r2cYPKwkG_L89e3mxRZ2eTURlU"
authDomain = "harija-fd51a.firebaseapp.com"
projectId = "harija-fd51a"
storageBucket = "harija-fd51a.appspot.com"
messagingSenderId = "200493090243"
appId = "1:200493090243:web:ce14d294e3476f98596976"
measurementId = "G-X5TK699K7M"

[fathomAnalytics]

[buymeacoffee]

[verification]
